apiVersion: v1
kind: Service
metadata:
  name: web-service-svc
spec:
  selector:
    app: web-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  labels:
    app: web-service
data:
  upstreamNameservers:
    ["8.8.8.8"]
spec:
  replicas: "{{ replicas }}"
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
        - name: web-service
          image: "{{ image }}"
          ports:
            - containerPort: 80
          imagePullPolicy: Never
